name: node-js pipeline QA

on:
  workflow_call:
    inputs:

      DOCKER_REPO:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      DOCKER_FILE_PATH:
        required: true
        type: string

env: 
  DOCKER_REPO: ${{ inputs.DOCKER_REPO }}
  IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
  DOCKER_FILE_PATH: ${{ inputs.DOCKER_FILE_PATH }}

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ env.DOCKER_FILE_PATH }}
          push: true
          tags: ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
